/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pratikum12062025;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PolaPerulangan extends javax.swing.JFrame {

    /**
     * Creates new form PolaPerulangan
     */
    public PolaPerulangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelAngka1 = new javax.swing.JLabel();
        LabelAngka2 = new javax.swing.JLabel();
        txtAngka1 = new javax.swing.JTextField();
        txtAngka2 = new javax.swing.JTextField();
        LabelProses = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        cbPola = new javax.swing.JComboBox<>();
        areaHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("POLA PERULANGAN");

        LabelAngka1.setText("Masukkan Angka1");

        LabelAngka2.setText("Masukkan Angka2");

        LabelProses.setText("Proses");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        cbPola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pola1", "Pola2", "Pola3", "Pola4", " " }));

        areaHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaHasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelAngka2)
                            .addComponent(LabelAngka1))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAngka2)
                            .addComponent(cbPola, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAngka1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnProses)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelProses)
                        .addGap(27, 27, 27)
                        .addComponent(areaHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAngka1)
                    .addComponent(txtAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAngka2)
                    .addComponent(txtAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelProses)
                    .addComponent(btnProses)
                    .addComponent(cbPola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(areaHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaHasilActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
       try{
       int a = Integer.parseInt(txtAngka1.getText());
       int b = Integer.parseInt(txtAngka2.getText());
       int pil = (int) cbPola.getSelectedIndex();
       
       StringBuilder pola = new StringBuilder("Tampilkan Pola \n\n");
       
       
       switch(pil){
           case 1 : for(int i=1;i<=a;i++){
                        for(int j=1;j<=b;j++){
                            pola.append(" * ");
                        }
                        pola.append("\n");
           }
           break;
           case 2 : for (int i = a; i >= 1; i--) {
                        for (int j = 1; j <= b; j++) {
                            if (j <= i) {
                                 pola.append(" "+(i * j)+" "); 
                            } else {
                                pola.append("    "); 
                                    }
                            }
                        pola.append("\n");
                }
           break;
           case 3 : for(int i=1;i<=a;i++){
                        for(int j=1;j<=b;j++)
                            pola.append("");
                        
                        {
                            switch (i%4) {
                                case 1:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" # ");
                                    break;
                                case 2:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" 2 ");
                                    break;
                                case 3:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" * ");
                                    break;
                                default:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" - ");
                                    break;
                            }
                        }
                    pola.append("\n");
       }
       break;
           default : char symbol = '*'; 
                     if (b == 1) symbol = '*';
                    else if (b == 2) symbol = '#';
                    else if (b == 3) symbol = '@';
                for (int i = 1; i <= a; i++) {
                        for (int j = 1; j <= a - i; j++) {
                    pola.append(" ");
                    }   
        
                    for (int k = 1; k <= 2 * i - 1; k++) {
                    pola.append(symbol);
                    }
                    pola.append("\n");
                    }
    
                    for (int i = a - 1; i >= 1; i--) {
                        for (int j = 1; j <= a - i; j++) {
                        pola.append(" ");
                    }
        
                    for (int k = 1; k <= 2 * i - 1; k++) {
                        pola.append(symbol);
                    }
                    pola.append("\n");

        }
           break;
       }
       areaHasil.setText(pola.toString());
       }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Masukan angka valid ","Input Error",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnProsesActionPerformed
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
        txtAngka1.setText("");
        txtAngka2.setText("");
        cbPola.setSelectedIndex(0);
        areaHasil.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolaPerulangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAngka1;
    private javax.swing.JLabel LabelAngka2;
    private javax.swing.JLabel LabelProses;
    private javax.swing.JTextField areaHasil;
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox<String> cbPola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAngka1;
    private javax.swing.JTextField txtAngka2;
    // End of variables declaration//GEN-END:variables
}
