/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasKelasPengganti;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PolaPerulangan extends javax.swing.JFrame {

    /**
     * Creates new form PolaPerulangan
     */
    public PolaPerulangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPola = new javax.swing.JLabel();
        LabelAngka1 = new javax.swing.JLabel();
        LabelAngka2 = new javax.swing.JLabel();
        txtAngka1 = new javax.swing.JTextField();
        txtAngka2 = new javax.swing.JTextField();
        LabelProses = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        cbPola = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaHasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelPola.setText("POLA PERULANGAN");

        LabelAngka1.setText("Masukkan Angka1");

        LabelAngka2.setText("Masukkan Angka2");

        LabelProses.setText("Proses");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        cbPola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pola1", "Pola2", "Pola3", "Pola4", "Pola5", "Pola6", "Pola7", " " }));

        btnReset.setText("Reset");

        btnKeluar.setText("Keluar");

        areaHasil.setColumns(20);
        areaHasil.setRows(5);
        jScrollPane1.setViewportView(areaHasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelAngka2)
                    .addComponent(LabelAngka1))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAngka2)
                    .addComponent(cbPola, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAngka1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnProses)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(LabelPola))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(LabelProses)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(LabelPola)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAngka1)
                    .addComponent(txtAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProses)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(LabelAngka2)
                        .addGap(18, 18, 18)
                        .addComponent(LabelProses)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(26, 26, 26)
                        .addComponent(btnKeluar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
     try {
    // Validasi input
    if (txtAngka1.getText().isEmpty() || txtAngka2.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan kedua angka terlebih dahulu", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    int a = Integer.parseInt(txtAngka1.getText());
    int b = Integer.parseInt(txtAngka2.getText());
    int pil = cbPola.getSelectedIndex() + 1; // Karena index dimulai dari 0
    
    // Validasi nilai input
    if (a <= 0 || b <= 0) {
        JOptionPane.showMessageDialog(this, "Masukkan angka positif lebih besar dari 0", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    StringBuilder pola = new StringBuilder("=== Pola " + pil + " ===\n\n");
    
    switch(pil) {
        case 1: 
            // Pola 1: Persegi panjang bintang
            for(int i = 1; i <= a; i++) {
                for(int j = 1; j <= b; j++) {
                    pola.append(" * ");
                }
                pola.append("\n");
            }
            break;
            
        case 2: 
            // Pola 2: Segitiga angka perkalian
          
           for (int i = a; i >= 1; i--) {
                    for (int j = 1; j <= b; j++) {
                        if (j <= i) {
                            pola.append(String.format("%2d ", (i * j))); 
                        } else {
                            pola.append("    "); 
                        }
                    }
                    pola.append("\n");
                }
                break;
        case 3: 
            // Pola 3: Pola bergantian simbol
            for(int i = 1; i <= a; i++) {
                switch (i % 4) {
                    case 1:
                        for (int j = 1; j <= b; j++)
                            pola.append(" # ");
                        break;
                    case 2:
                        for (int j = 1; j <= b; j++)
                            pola.append(" 2 ");
                        break;
                    case 3:
                        for (int j = 1; j <= b; j++)
                            pola.append(" * ");
                        break;
                    default:
                        for (int j = 1; j <= b; j++)
                            pola.append(" - ");
                        break;
                }
                pola.append("\n");
            }
            break;
            
        case 4: 
            // Pola 4: Berlian dengan simbol berbeda
            char symbol = '*';
            if (b == 1) symbol = '*';
            else if (b == 2) symbol = '#';
            else if (b == 3) symbol = '@';
            
            // Bagian atas berlian
            for (int i = 1; i <= a; i++) {
                for (int j = 1; j <= a - i; j++) {
                    pola.append(" ");
                }   
                for (int k = 1; k <= 2 * i - 1; k++) {
                    pola.append(symbol);
                }
                pola.append("\n");
            }
            
            // Bagian bawah berlian
            for (int i = a - 1; i >= 1; i--) {
                for (int j = 1; j <= a - i; j++) {
                    pola.append(" ");
                }
                for (int k = 1; k <= 2 * i - 1; k++) {
                    pola.append(symbol);
                }
                pola.append("\n");
            }
            break;
            
        case 5: 
            // Pola 5: Segitiga dengan diagonal
            for (int i = 1; i <= a; i++) {
                for (int j = 1; j <= b; j++) {
                    if (i == 1 || j == 1 || i == j) {
                        pola.append("0 ");
                    } else {
                        pola.append("* ");
                    }
                }
                pola.append("\n");
            }
            break;
            
        case 6: 
            // Pola 6: Segitiga ganda dengan outline
            // Bagian atas
            for(int i = 1; i <= a; i++) {
                for(int j = b; j >= i; j--) {
                    if(i == a || j == b || j == i) {
                        pola.append(" * ");
                    } else {
                        pola.append("   ");
                    }
                }
                pola.append("\n");
            }
            
            // Bagian bawah
            for(int i = 2; i <= a; i++) {
                for(int j = 1; j <= i; j++) {
                    if(j == 1 || j == i) {
                        pola.append(" * ");
                    } else {
                        pola.append("   ");
                    }
                }
                pola.append("\n");
            }
            break;
            
        default: 
            // Pola default: Huruf T
            int mid = (b + 1) / 2;
            for (int i = 1; i <= a; i++) {
                for (int j = 1; j <= b; j++) {
                    if (i == 1 || j == mid) {
                        pola.append("T ");
                    } else {
                        pola.append("  ");
                    }
                }
                pola.append("\n");
            }
    }
    
    areaHasil.setText(pola.toString());
    
} catch(NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Masukkan angka yang valid", "Input Error", JOptionPane.ERROR_MESSAGE);
    txtAngka1.requestFocus();
}
}
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {                                    
    txtAngka1.setText("");
    txtAngka2.setText("");
    cbPola.setSelectedIndex(0);
    areaHasil.setText("");
    txtAngka1.requestFocus();
}

private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {                                    
    int pilihan = JOptionPane.showConfirmDialog(
        this, 
        "Apakah Anda yakin ingin keluar?", 
        "Konfirmasi Keluar", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    
    if(pilihan == JOptionPane.YES_OPTION) {
        System.exit(0);
    }

    }//GEN-LAST:event_btnProsesActionPerformed
  
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolaPerulangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAngka1;
    private javax.swing.JLabel LabelAngka2;
    private javax.swing.JLabel LabelPola;
    private javax.swing.JLabel LabelProses;
    private javax.swing.JTextArea areaHasil;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbPola;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAngka1;
    private javax.swing.JTextField txtAngka2;
    // End of variables declaration//GEN-END:variables
}
